---

- name: get Cluster IP Address
  shell: |
    prodserv=$( cat /tmp/prod.config | grep "server: https" )
    devserv=$( cat /tmp/dev.config | grep "server: https" )
    prodca=$( cat /tmp/prod.config | grep "certificate-authority-data" )
    devca=$( cat /tmp/dev.config | grep "certificate-authority-data" )
    produsercert=$( cat /tmp/prod.config | grep "client-certificate-data" )
    devusercert=$( cat /tmp/dev.config | grep "client-certificate-data" )
    produserkey=$( cat /tmp/prod.config | grep "client-key-data" )
    devuserkey=$( cat /tmp/dev.config | grep "client-key-data" )
    echo "apiVersion: v1" > /tmp/kubeconfig
    echo "kind: Config" >> /tmp/kubeconfig
    echo "preferences: {}" >> /tmp/kubeconfig
    echo "current-context: dev-context" >> /tmp/kubeconfig
    echo "clusters:" >> /tmp/kubeconfig
    echo "- cluster:" >> /tmp/kubeconfig
    echo "$prodca" >> /tmp/kubeconfig
    echo "$prodserv" >> /tmp/kubeconfig
    echo "  name: prod-cluster" >> /tmp/kubeconfig
    echo "- cluster:" >> /tmp/kubeconfig
    echo "$devca" >> /tmp/kubeconfig
    echo "$devserv" >> /tmp/kubeconfig
    echo "  name: dev-cluster" >> /tmp/kubeconfig
    echo "contexts:" >> /tmp/kubeconfig
    echo "- context:" >> /tmp/kubeconfig
    echo "    cluster: prod-cluster" >> /tmp/kubeconfig
    echo "    user: prod-user" >> /tmp/kubeconfig
    echo "  name: prod-context" >> /tmp/kubeconfig
    echo "- context:" >> /tmp/kubeconfig
    echo "    cluster: dev-cluster" >> /tmp/kubeconfig
    echo "    user: dev-user" >> /tmp/kubeconfig
    echo "  name: dev-context" >> /tmp/kubeconfig
    echo "users:" >> /tmp/kubeconfig
    echo "- name: prod-user" >> /tmp/kubeconfig
    echo "  user:" >> /tmp/kubeconfig
    echo "$produsercert" >> /tmp/kubeconfig
    echo "$produserkey" >> /tmp/kubeconfig
    echo "- name: dev-user" >> /tmp/kubeconfig
    echo "  user:" >> /tmp/kubeconfig
    echo "$devusercert" >> /tmp/kubeconfig
    echo "$devuserkey" >> /tmp/kubeconfig
  args:
    executable: /bin/bash
  connection: local
  changed_when: false

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /tmp/kubeconfig
    dest: /etc/rancher/k3s/k3s.yaml
    owner: root
    group: root
    mode: '0644'
  connection: ssh
