---

- name: get Cluster IP Address
  shell: getent hosts {{ cluster_host }} | awk '{ print $1 }'
  args:
    executable: /bin/bash
  connection: local
  register: cluster_ip
  changed_when: false

- name: Wait for {{ cluster_ip.stdout }} started 
  wait_for:
    port: 22
    host: '{{ cluster_ip.stdout }}'
    search_regex: OpenSSH
    delay: 1
    timeout: 30
  connection: local
  register: started
  changed_when: false

- name: Copy config
  ansible.builtin.fetch:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "/tmp/{{ cluster_env }}.config"
    flat: yes
  connection: ssh
  when: '"started" in started.state'
  vars:
    ansible_host: "{{ cluster_ip.stdout }}"
  changed_when: false

- name: save cluster IP
  shell: sed -i -e 's/127.0.0.1/{{ cluster_ip.stdout }}/g' "/tmp/{{ cluster_env }}.config"
  args:
    executable: /bin/bash
  connection: local
  changed_when: false
