---

- name: Add Helm charts repository
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Deploy cert manager
  kubernetes.core.helm:
    name: alex-cluster-certmgr
    chart_ref: jetstack/cert-manager
    release_namespace: alex-cluster-certmgr
    create_namespace: true
    force: true
    kubeconfig_path: /etc/rancher/k3s/config.yaml
    values:
      installCRDs: true

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - golang-go

- name: Install cmctl
  shell: |
    OS=$(go env GOOS); ARCH=$(go env GOARCH); curl -fsSL -o cmctl.tar.gz https://github.com/cert-manager/cert-manager/releases/download/v1.8.2/cmctl-$OS-$ARCH.tar.gz
    tar xzf cmctl.tar.gz
    mv cmctl /usr/local/bin
  args:
    executable: /bin/bash

- name: Test cmctl
  shell: |
    cmctl version --kubeconfig /etc/rancher/k3s/config.yaml
  args:
    executable: /bin/bash
