---

- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip

- name: Test k3s installed
  shell: kubectl version
  args:
    executable: /bin/bash
  register: validateresult
  changed_when: 'false'
  failed_when: 'false'

- name: Install k3s
##  shell: 'curl -sfL https://get.k3s.io | sh -s - server --datastore-endpoint="mysql://{{ param_k3s_admin_username }}:{{ param_k3s_admin_password }}@tcp({{ param_hostname }}:3306)/{{ param_k3s_database }}" --no-deploy servicelb --no-deploy traefik'
  shell: 'curl -sfL https://get.k3s.io | sh -'
  args:
    executable: /bin/bash
  when: '"kubectl: command not found" in validateresult.stderr'
##  register: result
##  changed_when:
##  - 'not ("Found existing file" in result.stderr)'

- name: Copy profile file
  ansible.builtin.template:
    src: "profile.k3s.sh.j2"
    dest: "/etc/profile.d/profile.k3s.sh"
    owner: root
    group: root
    mode: 0777
